// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3XVzY16V0SUhujPwAYBIF0QcPOn-aChA',
    appId: '1:979671915039:web:66de7211f76fc9e039532a',
    messagingSenderId: '979671915039',
    projectId: 'greenreviveapp-40cd2',
    authDomain: 'greenreviveapp-40cd2.firebaseapp.com',
    storageBucket: 'greenreviveapp-40cd2.firebasestorage.app',
    measurementId: 'G-NK2FDH954Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSfCQWP3r_xes2iS2cJ1coXd6FqraanOY',
    appId: '1:979671915039:android:714d5f936aef333b39532a',
    messagingSenderId: '979671915039',
    projectId: 'greenreviveapp-40cd2',
    storageBucket: 'greenreviveapp-40cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKXewDRoo3Gl1wGmhPupjRD1lLq7ObXoY',
    appId: '1:979671915039:ios:44b6108ef0b5cb6439532a',
    messagingSenderId: '979671915039',
    projectId: 'greenreviveapp-40cd2',
    storageBucket: 'greenreviveapp-40cd2.firebasestorage.app',
    iosBundleId: 'com.example.greenreviveapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKXewDRoo3Gl1wGmhPupjRD1lLq7ObXoY',
    appId: '1:979671915039:ios:44b6108ef0b5cb6439532a',
    messagingSenderId: '979671915039',
    projectId: 'greenreviveapp-40cd2',
    storageBucket: 'greenreviveapp-40cd2.firebasestorage.app',
    iosBundleId: 'com.example.greenreviveapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3XVzY16V0SUhujPwAYBIF0QcPOn-aChA',
    appId: '1:979671915039:web:bfc668830324071a39532a',
    messagingSenderId: '979671915039',
    projectId: 'greenreviveapp-40cd2',
    authDomain: 'greenreviveapp-40cd2.firebaseapp.com',
    storageBucket: 'greenreviveapp-40cd2.firebasestorage.app',
    measurementId: 'G-TM3ERTW13F',
  );
}
